configuration:
  mongo:
    uri: mongodb://localhost:27017/
    database: bigdata
    input_collection: measurements
    output_collection: batch_views
  sources: 295
  attributes:
    - temperature
    - humidity
  measurements_in_block: 84
  time_line:
    from: 2018-01-01
    to: 2018-01-06
  values:
    minimum: 0.0
    q1: 2.0
    median: 5.0
    q3: 50.0
    maximum: 200.0
